name: linting, testing, building
on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master
jobs:
 build:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [17.x]
  steps:
   - uses: actions/checkout@v4
   - name: Starting Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node-version }}
   - name: install modules
     run: yarn
   - name: build production project
     run: npm run build:prod
   - name: linting typescript
     run: npm run lint:ts
   - name: linting css
     run: npm run lint:scss
   - name: checking formatting
     run: npm run format
   - name: unit testing
     run: npm run test:unit
   - name: ui testing
     run: npm run test:ui